name: call-build
on:
    push:
        branches:
            - main
jobs:
    build:
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            app_name: "my-web-app"
            environment: "production"
        secrets:
            DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    display-version:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Print build version
              run: 'echo "Build version is: ${{ needs.build.outputs.build_version }}"'