name: manual trigger
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "environment to deploy to"
                required: true
                type: choice
                options:
                    - staging
                    - development

jobs:
    environment-input:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment }}
    
        steps:
            - name: Deploy to ${{ github.event.inputs.environment }}
              run: echo "Deploying to ${{ github.event.inputs.environment }}"

