name: reusable-workflow
on:
    workflow_call:
        inputs:
            app_name:
                type: string
                required: true
            environment:
                type: string
                required: true
                default: staging
        secrets:
            DOCKERHUB_TOKEN:
                required: true
        
        outputs:
            build_version:
                description: "Generated build version"
                value: ${{ jobs.check.outputs.build_version }}

jobs:
    check:
        runs-on: ubuntu-latest

        outputs:
          build_version: ${{ steps.version.outputs.build_version }}

        steps:
            - name: checkout code
              uses: actions/checkout@v5
            - name: Build application
              run: |
                echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"
            
            - name: Check Docker token
              env:
                DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
              run: |
                    if [ -n "$DOCKER_TOKEN" ]; then
                        echo "Docker token is set: true"
                    else
                        echo "Docker token is set: false"
                    fi

            - name: generate build version
              id: version
              run: |
                SHORT_SHA=$(git rev-parse --short HEAD)
                VERSION="v1.0-${SHORT_SHA}"

                echo "Build version: $VERSION"
                echo "build_version=$VERSION" >> "$GITHUB_OUTPUT"


