name: smart-triggers
on:
    push:
        branches:
            - main
            - 'release/*'
        paths:
            - 'src/**'
            - 'app/**'
jobs:
    checking-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4


