name: smart-pipeline
on:
    push:
        branches: 
            - '**'
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: running linting
          run: running linting

    test:
        runs-on: ubuntu-latest
        steps:
            - name: running tests
              run: running tests

    summary:
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: pipeline summary
              run: |
                if [ "$GITHUB_REF" = "refs/heads/main" ]; then
                    echo " this is a main branch"
                else
                    echo "this is a feature branch"
                fi

                echo "commit message"
                echo "${{github.event.head_commit.message}}"